name: crowd_sense
description: Intelligent Crowd Monitoring and Emergency Alert System for PUP CEA Building.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^8.0.2
  fl_chart: ^1.1.1
  font_awesome_flutter: ^11.0.0
  animate_do: ^4.2.0
  glassmorphism: ^3.0.0
  provider: ^6.1.5+1
  window_manager: ^0.5.1
  intl: ^0.20.2
  firebase_core: ^4.6.0
  firebase_database: ^12.2.0
  firebase_auth: ^6.3.0
  http: ^1.6.0
  mailer: ^7.1.0
  flutter_dotenv: ^6.0.0
  cloud_functions: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/crowdsense_logo_blue.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/crowdsense_logo_blue.png"
    background_color: "#0F172A"
    theme_color: "#3B82F6"
  windows:
    generate: true
    image_path: "assets/images/crowdsense_logo_blue.png"
    icon_size: 256
  macos:
    generate: true
    image_path: "assets/images/crowdsense_logo_blue.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env

